"""phase 2 models

Revision ID: 35ec28ef0506
Revises: 
Create Date: 2026-09-05 00:21:40.116911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35ec28ef0506'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('razorpay_account_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_razorpay_account_id'), 'merchants', ['razorpay_account_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('entity_name', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_name', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_merchant_created', 'audit_logs', ['merchant_id', 'created_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_customer_id', sa.String(length=64), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'razorpay_customer_id', name='uq_merchant_razorpay_customer')
    )
    op.create_index('ix_customers_merchant_email', 'customers', ['merchant_id', 'email_hash'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_index('ix_customers_merchant_phone', 'customers', ['merchant_id', 'phone_hash'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_received_at'), 'webhook_events', ['received_at'], unique=False)
    op.create_index('ix_webhook_events_type_status', 'webhook_events', ['event_type', 'processing_status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_context', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='chk_payment_amount_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_merchant_status', 'payments', ['merchant_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('bank_or_issuer', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('error_source', sa.String(length=64), nullable=True),
    sa.Column('error_step', sa.String(length=64), nullable=True),
    sa.Column('error_reason', sa.String(length=64), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_attempts_payment_attempt_number', 'payment_attempts', ['payment_id', 'attempt_number'], unique=False)
    op.create_index(op.f('ix_payment_attempts_razorpay_payment_id'), 'payment_attempts', ['razorpay_payment_id'], unique=True)
    op.create_table('recovery_cases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('trigger_attempt_id', sa.UUID(), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revenue_at_risk', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['trigger_attempt_id'], ['payment_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_created_at'), 'recovery_cases', ['created_at'], unique=False)
    op.create_index('ix_recovery_cases_merchant_status', 'recovery_cases', ['merchant_id', 'status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_payment_id'), 'recovery_cases', ['payment_id'], unique=True)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('failure_category', sa.String(length=64), nullable=False),
    sa.Column('is_retryable', sa.Boolean(), nullable=False),
    sa.Column('root_cause_summary', sa.String(length=255), nullable=False),
    sa.Column('raw_error_code', sa.String(length=64), nullable=True),
    sa.Column('raw_error_description', sa.Text(), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('diagnosed_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_recovery_case_id'), 'diagnoses', ['recovery_case_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('features_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('recovery_probability_retry', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('recovery_probability_link', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('recovery_probability_nudge', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('recovery_probability_link >= 0 AND recovery_probability_link <= 1', name='chk_pred_prob_link_range'),
    sa.CheckConstraint('recovery_probability_nudge >= 0 AND recovery_probability_nudge <= 1', name='chk_pred_prob_nudge_range'),
    sa.CheckConstraint('recovery_probability_retry >= 0 AND recovery_probability_retry <= 1', name='chk_pred_prob_retry_range'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 1', name='chk_pred_risk_score_range'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_recovery_case_id'), 'predictions', ['recovery_case_id'], unique=False)
    op.create_table('recovery_measurements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('attribution_status', sa.String(length=64), nullable=False),
    sa.Column('verified_recovered_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('resolution_attempt_id', sa.UUID(), nullable=True),
    sa.Column('resolution_webhook_event_id', sa.UUID(), nullable=True),
    sa.Column('time_to_recovery_seconds', sa.Integer(), nullable=True),
    sa.Column('attribution_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('measured_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.ForeignKeyConstraint(['resolution_attempt_id'], ['payment_attempts.id'], ),
    sa.ForeignKeyConstraint(['resolution_webhook_event_id'], ['webhook_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_measurements_recovery_case_id'), 'recovery_measurements', ['recovery_case_id'], unique=True)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('recommended_intervention', sa.String(length=64), nullable=False),
    sa.Column('ranking_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_recoverable_amount', sa.BigInteger(), nullable=False),
    sa.Column('recommended_execution_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('recommended_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_recovery_case_id'), 'recommendations', ['recovery_case_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('evaluated_intervention', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('rules_evaluated', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejection_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_decisions_case_decision', 'policy_decisions', ['recovery_case_id', 'decision'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('policy_decision_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('external_reference_id', sa.String(length=128), nullable=True),
    sa.Column('execution_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], ),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_idempotency_key'), 'recovery_actions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_recovery_actions_recovery_case_id'), 'recovery_actions', ['recovery_case_id'], unique=False)
    op.create_index('ix_recovery_actions_status_scheduled', 'recovery_actions', ['status', 'scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_actions_status_scheduled', table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_recovery_case_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_idempotency_key'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('ix_policy_decisions_case_decision', table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_recommendations_recovery_case_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_recovery_measurements_recovery_case_id'), table_name='recovery_measurements')
    op.drop_table('recovery_measurements')
    op.drop_index(op.f('ix_predictions_recovery_case_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_diagnoses_recovery_case_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_recovery_cases_payment_id'), table_name='recovery_cases')
    op.drop_index('ix_recovery_cases_merchant_status', table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_created_at'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_payment_attempts_razorpay_payment_id'), table_name='payment_attempts')
    op.drop_index('ix_payment_attempts_payment_attempt_number', table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index('ix_payments_merchant_status', table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_webhook_events_type_status', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_received_at'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_customers_merchant_phone', table_name='customers')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index('ix_customers_merchant_email', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_audit_logs_merchant_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_merchants_razorpay_account_id'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
