"""phase_5_policy_decision_update

Revision ID: 8793878b3fad
Revises: cfdd4abb8328
Create Date: 2026-09-05 01:54:24.393963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8793878b3fad'
down_revision: Union[str, Sequence[str], None] = 'cfdd4abb8328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_decisions', sa.Column('diagnosis_id', sa.UUID(), nullable=False))
    op.alter_column('policy_decisions', 'recommendation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_policy_decisions_diagnosis_id'), 'policy_decisions', ['diagnosis_id'], unique=False)
    op.create_foreign_key(None, 'policy_decisions', 'diagnoses', ['diagnosis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policy_decisions', type_='foreignkey')
    op.drop_index(op.f('ix_policy_decisions_diagnosis_id'), table_name='policy_decisions')
    op.alter_column('policy_decisions', 'recommendation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('policy_decisions', 'diagnosis_id')
    # ### end Alembic commands ###
